### ISSUE TITLE
User should be able to perform multi-file upload. Currently, this is not possible (PASS)

### ISSUE THREAD

**Issue by MHEBE3ET** [dotbc/dotbc-queue-site#1]

**Comment by mateodelnorte** [comment]
Happy to put it in, but it wasn't an original requirement. @christse Would you like multi-upload?

**Comment by christse** [comment]
An SFTP approach will have multi-file upload. So, yes.

**Comment by mateodelnorte** [comment]
fixed in 889a6aa9f04150e3809d277c05eb4dd2c6efb8bf. will auto-deploy shortly.

**Comment by MHEBE3ET** [comment]
PASS
