### ISSUE TITLE
Dismissing the dialog, breaks styling of the home page

### ISSUE THREAD

**Issue by MHEBE3ET** [dotbc/dotbc-queue-site#19]
Repro:
-navigate to home page
-delete Name -> error message is displayed
-dismiss error message

Issue description:
-Styling is broken

**Comment by MHEBE3ET** [comment]
![untitled2](https://cloud.githubusercontent.com/assets/13591955/21063227/84a27540-be22-11e6-89f5-3885a8a0016d.png)
![untitled3](https://cloud.githubusercontent.com/assets/13591955/21063228/84add552-be22-11e6-90fc-c5a5142cb6ef.png)

**Comment by mateodelnorte** [comment]
Fixed by 1e2a532.
