### ISSUE TITLE
 Login page error message styling needs some TLC

### ISSUE THREAD

**Issue by MHEBE3ET** [dotbc/dotbc-queue-site#25]
![untitled14](https://cloud.githubusercontent.com/assets/13591955/21078173/6e162df4-bf34-11e6-854c-6ac0ed5cae74.png)
![untitled15](https://cloud.githubusercontent.com/assets/13591955/21078174/6e18753c-bf34-11e6-847d-05701f3421d6.png)

**Comment by mateodelnorte** [comment]
Any new design changes should probably come from @briancfeeney. Here's what the component looks like now, with 'forgot password' added to it: 

<img width="336" alt="screen shot 2016-12-11 at 12 02 12 am" src="https://cloud.githubusercontent.com/assets/554847/21078208/1ba4b620-bf35-11e6-8ef0-4810c9f77cc0.png">

**Comment by mateodelnorte** [comment]
Text now matches monograph: 

<img width="329" alt="screen shot 2016-12-11 at 12 12 09 am" src="https://cloud.githubusercontent.com/assets/554847/21078263/7ef4a324-bf36-11e6-837b-0b5c67c1d3fc.png">

For any updated styling, we'll have to ask @briancfeeney and @christse for priority.

**Comment by MHEBE3ET** [comment]
If design has already been solidified, no reason to change anything
