### ISSUE TITLE
In Queue list does not match between what Admin sees and what Anauth user sees

### ISSUE THREAD

**Issue by MHEBE3ET** [dotbc/dotbc-queue-site#26]
![auth_queue](https://cloud.githubusercontent.com/assets/13591955/21087125/102439c6-bff1-11e6-91b1-2245b911a848.png)
![unauth_queue](https://cloud.githubusercontent.com/assets/13591955/21087126/102474d6-bff1-11e6-91fe-5cd27556b883.png)

**Comment by mateodelnorte** [comment]
Fixed by 7c81ca5. Will auto-deploy momentarily.
