### ISSUE TITLE
User positioning is the Queue is not working properly. Gap in numbers

### ISSUE THREAD

**Issue by MHEBE3ET** [dotbc/dotbc-queue-site#3]

**Comment by MHEBE3ET** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13591955/20863821/61052b70-b9a7-11e6-9333-bc4647d3ce45.png)
![untitled1](https://cloud.githubusercontent.com/assets/13591955/20863822/647e0452-b9a7-11e6-9663-cbd07e86ae98.png)

**Comment by MHEBE3ET** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13591955/20863833/7a5b7e6c-b9a7-11e6-979d-79d7604022b3.png)

**Comment by MHEBE3ET** [comment]
![untitled3](https://cloud.githubusercontent.com/assets/13591955/20863885/45d6da22-b9a9-11e6-9030-7159d62b036d.png)

**Comment by mateodelnorte** [comment]
Can you submit steps for reproducing? I'm unable to repro.

**Comment by MHEBE3ET** [comment]
As I started accepting users noticed that In Queue numbers are incorrect. For example below

![untitled3](https://cloud.githubusercontent.com/assets/13591955/20891070/46824c52-bad7-11e6-834b-e4eea91bfca4.png)

**Comment by mateodelnorte** [comment]
Having difficulty reproducing locally. Going to put some increased logging in to see what's happening. May be particular to the prod environment.

**Comment by mateodelnorte** [comment]
Ok. Finally got it going on prod. Fix coming shortly.

**Comment by MHEBE3ET** [comment]
This is still an issue

**Comment by MHEBE3ET** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13591955/21061797/d9a3af8e-be1b-11e6-92c7-ea434f36a6ad.png)

**Comment by mateodelnorte** [comment]
Yup. I've got the fix nearly done on my local, just had to run to a meeting before finishing. Will push this eve. You'll see the issue close to signify the code push.

**Comment by mateodelnorte** [comment]
Fixed with 5a2768956940cd880edd1558eb4fea4355ce9609.
