### ISSUE TITLE
Make start error

### ISSUE THREAD

**Issue by MikeiseenKoning** [dotbc/dotbc-queue-site#35]
Whenever I run make start it gives me te following return:

Makefile:7: *** Recursive variable `MAILGUN_API_KEY' references itself (eventually).  Stop.

How do I solve this error?

Thanks in advance

**Comment by mateodelnorte** [comment]
You need to create a mailgun api key in mailgun's admin interface and provide it as an environment variable as MAILGUN_API_KEY.
