### ISSUE TITLE
Able to save profile with required values blank, causing havoc. (PASS)

### ISSUE THREAD

**Issue by MHEBE3ET** [dotbc/dotbc-queue-site#6]
![untitled6](https://cloud.githubusercontent.com/assets/13591955/20863957/fe90ad98-b9ab-11e6-9ff9-0072ca905773.png)

**Comment by MHEBE3ET** [comment]
![untitled7](https://cloud.githubusercontent.com/assets/13591955/20863959/043c1d22-b9ac-11e6-9998-7711c3eb5ea3.png)

**Comment by MHEBE3ET** [comment]
User: apalat@mailinator.com
Pwd: abc123

Also, unable make these columns editable again. Thus the user is screwed.

**Comment by mateodelnorte** [comment]
What's your browser version? Modern browsers should be respecting the 'required' property. I can put in a polyfill or use a validation library to ensure for older browsers. 

<img width="559" alt="screen shot 2016-12-04 at 9 51 33 pm" src="https://cloud.githubusercontent.com/assets/554847/20872414/41b9bcac-ba6c-11e6-8e7d-0b06af3f65d0.png">

**Comment by MHEBE3ET** [comment]
The bug is not that you are able to submit profile with required fields blank. You are able to update the profile with required field blank.

**Comment by mateodelnorte** [comment]
Got it. Please provide clear steps to reproduce in addition to images, otherwise it's not clear to me what needs to be fixed.

**Comment by mateodelnorte** [comment]
Fixed by 1cf4f04000bab03e9d628210563ee2800d25dff6.

**Comment by MHEBE3ET** [comment]
Please style validation better, if you have time (Not a deal-breaker). Use the same validator you are using on registration page

![untitled1](https://cloud.githubusercontent.com/assets/13591955/21062919/1204d222-be21-11e6-9ef0-c5259ac9b0c6.png)
